services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: libraryuser
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: librarydb
    ports:
      - "5333:5432"
    volumes:
      - library_db:/var/lib/postgresql/data

volumes:
  library_db: